---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequotas/finalizers
  verbs:
  - update
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequotas/status
  verbs:
  - get
  - patch
  - update
