---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - resourcequota
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequota/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - resourcequota/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequota
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequota/finalizers
  verbs:
  - update
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequota/status
  verbs:
  - get
  - patch
  - update
