# permissions for end users to view tenantresourcequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenantresourcequota-viewer-role
rules:
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequota
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - necotiator.cybozu.io
  resources:
  - tenantresourcequota/status
  verbs:
  - get
