apiVersion: necotiator.cybozu.io/v1beta1
kind: TenantResourceQuota
metadata:
  name: tenantresourcequota-sample
spec:
  # TODO(user): Add fields here
  namespaceSelector:
    matchLabels:
      team: neco
  hard:
    requests.cpu: "100m"
    requests.memory: "100m"
