[book]
language = "en"
multilingual = false
src = "."
title = "Template Documentation"

[output.html]
git-repository-url = "https://github.com/cybozu-go/necotiator"
edit-url-template = "https://github.com/cybozu-go/necotiator/edit/main/docs/{path}"
site-url = "/necotiator/"
